apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "track-cbf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "track-cbf.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | default "0 */4 * * *" | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "track-cbf.name" . }}
            image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion ) }}
            imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
            args:
              - {{ .Values.event | default "cbf2023" }}
              {{- with .Values.extraArgs }}
                {{- . | toYaml | nindent 14 }}
              {{- end }}
              - --output-dir
              - /output
            volumeMounts:
            - name: output
              mountPath: /output
          restartPolicy: "Never"
          volumes:
          - name: output
            persistentVolumeClaim:
              claimName: {{ include "track-cbf.fullname" . }}
          affinity:
            nodeAffinity: 
              requiredDuringSchedulingIgnoredDuringExecution: {{ include "track-cbf.nodeAffinity" . | nindent 16 }}
