apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "track-cbf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "track-cbf.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.localPath | quote }}
  nodeAffinity:
    required: {{ include "track-cbf.nodeAffinity" . | nindent 6 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "track-cbf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "track-cbf.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels: {{ include "track-cbf.selectorLabels" . | nindent 6 }}
