---
name: Build

on:
  pull_request:
  push:
    branches:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20.3"

    - name: Go Test
      run: "go test -v -cover ./..."
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
